---
title: "Predicting abalone age from physical measurements"
author: "Huanhuan Li, Chuang Wang, Charles Suresh </br>"
date: "2020/11/28 (updated: `r Sys.Date()`)"
always_allow_html: true
output: 
  github_document:
    toc: true
   
bibliography: abalone_age_refs.bib
---

# Summary

To predict abalone's age from physical measurements, we build a regression model using a popular type of regularized linear regression model Ridge. The model can use the physical measurements(Sex, Length, Diameter, Height, Whole weight, etc.) to predict the age of abalone in decimal number. Our final Ridge model can predict age in a good accuracy on an unseen test data set, with $R^2$ score of ...... However, considering the potential economic losses to the stakeholders, we recommend further improvement before it is put into the industry.

# Methods

## Data
The dataset used in this project comes from an original study "The Population Biology of Abalone (_Haliotis_ species) in Tasmania. I. Blacklip Abalone (_H. rubra_) from the North Coast and Islands of Bass Strait", created by Warwick J Nash, Tracy L Sellers, Simon R Talbot, Andrew J Cawthorn and Wes B Ford (1994). It was sourced from the UCI Machine Learning Repository and can be found [here](http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/). Each row in the data set represents an abalone, including the physical measurements(Sex, Length, Diameter, Height, Whole weight, etc.) and the number of rings, which gives the age in years by adding 1.5. The missing values in the original study have been removed and the range of continuous values has been scaled. Please find the detailed information [here](http://archive.ics.uci.edu/ml/datasets/Abalone?pagewanted=all).


## Analysis
The Ridge model was used to build a regression model to predict abalone age based on the physical measures, which involve 1 categorical feature ("age"), and 7 numerical features ("Length", "Diameter", "Height", "Whole weight", "Shucked weight", "Viscera weight", and "Shell weight"). All features are contained in the original data set. The predicting target "age" is converted from the "rings" in the original data set by adding 1.5. Before fitting the model, we exclude 1 outlier with extremely large height, and apply a standard scale transformation on numerical features. The model parameter $alpha$ was chosen using a randomized search on hyperparameters in 5-fold cross-validation with $R^2$ as the evaluation metric.


The Python programming languages [@Python] and the following Python packages were used to perform the analysis: docopt [@docoptpython], Pandas [@pandas], Seaborn[@seaborn], Scikit-learn[@sklearn], Numpy[@numpy], Pickle[@pickle], Matplotlib[@hunter2007matplotlib] The code used to perform the analysis and create this report can be found here: https://github.com/UBC-MDS/Abalone_Age_Prediction.

# Results & Discussion




# Reference



